version: "3.8"

services:
  pihole:
    image: nginx
    ports:
      - 80:80/tcp
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/galea_lan_proxy.conf:/etc/nginx/conf.d/galea_lan_proxy.conf
    restart: unless-stopped
